baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mahliya'
theme = 'apsho-hugo-theme'
foo = 'bar'
[params]
logo_name = 'images/logo-name.png'
logo_symbol = 'images/logo-symbol.png'
app_image = 'image/app_image.svg'
contact_email = 'mahliya@example.org'
